#!/usr/bin/env bash
# install-scanners.sh — fetch & verify pinned Trivy + Semgrep (ADR-0028).
#
# Reads ``.scanner-versions`` for the pinned ``<name> <version>`` tuples and
# stages each scanner under ``${CLIFF_BIN_DIR:-bin}``. Layout:
#
#   bin/trivy     — extracted Trivy binary (chmod +x)
#   bin/semgrep   — wrapper that exec's a pinned semgrep venv
#
# Integrity model (ADR-0028, revised after PR #145 review):
#
# - **Trivy**  is verified against the upstream-published
#   ``trivy_<version>_checksums.txt`` from the same GitHub release tag.
#   That file is generated by aquasec/trivy CI and signed via cosign;
#   we don't re-pin it locally because every (os, arch) tarball has a
#   different digest and a single hash in ``.scanner-versions`` could
#   never match all platforms.
#
# - **Semgrep** is installed via ``pip`` from PyPI into a private venv.
#   Integrity comes from PyPI's per-wheel digests + TLS pin; we verify
#   the install by running ``semgrep --version`` and asserting the
#   pinned version. (The previous "wrapper-script SHA" check was
#   meaningless — the wrapper text changes per machine.)
#
# Strict mode is the default and the only mode: the script exits non-zero
# on any verification failure. There is no ``warn`` escape hatch; if
# verification fails we want the build / install to stop, because
# without working scanners every assessment fails at trivy_vuln.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS_FILE="${REPO_ROOT}/.scanner-versions"
BIN_DIR="${CLIFF_BIN_DIR:-${REPO_ROOT}/bin}"

if [[ ! -f "${VERSIONS_FILE}" ]]; then
  echo "error: ${VERSIONS_FILE} not found" >&2
  exit 1
fi
mkdir -p "${BIN_DIR}"

case "$(uname -s)" in
  Linux*)  OS="Linux";  IS_DARWIN=0 ;;
  Darwin*) OS="macOS";  IS_DARWIN=1 ;;
  *) echo "unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac

case "$(uname -m)" in
  x86_64|amd64)  ARCH="64bit"  ;;
  arm64|aarch64) ARCH="ARM64"  ;;
  *) echo "unsupported arch: $(uname -m)" >&2; exit 1 ;;
esac

# Trivy upstream releases are glibc-only. Fail early on musl (Alpine) instead
# of letting the user hit "file not found" at scan time.
#
# Capture ldd's output into a variable before grepping. Piping into
# ``grep -q`` under ``set -o pipefail`` makes ldd report a SIGPIPE write
# error and fails the pipeline even on glibc systems (the "no glibc"
# branch then fires by mistake).
if [[ "${OS}" == "Linux" ]] && command -v ldd >/dev/null 2>&1; then
  ldd_version_output="$(ldd --version 2>&1 || true)"
  if ! grep -qiE 'glibc|gnu libc' <<<"${ldd_version_output}"; then
    echo "error: this installer requires glibc Linux. Alpine/musl is not supported — use the Docker image instead." >&2
    exit 1
  fi
fi

strip_quarantine() {
  # Strip macOS quarantine so Gatekeeper doesn't block fresh downloads.
  if [[ "${IS_DARWIN}" == "1" ]] && command -v xattr >/dev/null 2>&1; then
    xattr -dr com.apple.quarantine "$1" 2>/dev/null || true
  fi
}

sha256_of() {
  # Portable across macOS (shasum) and most Linux (sha256sum). Fedora/RHEL
  # ship coreutils' sha256sum but not the perl shasum, while macOS is the
  # reverse — try both before failing.
  local file="$1"
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "${file}" | awk '{print $1}'
  elif command -v sha256sum >/dev/null 2>&1; then
    sha256sum "${file}" | awk '{print $1}'
  else
    echo "error: neither shasum nor sha256sum available" >&2
    exit 1
  fi
}

install_trivy() {
  local version="$1"
  local archive="trivy_${version}_${OS}-${ARCH}.tar.gz"
  local checksums_file="trivy_${version}_checksums.txt"
  local base_url="https://github.com/aquasecurity/trivy/releases/download/v${version}"
  local tmp
  tmp="$(mktemp -d)"

  echo "==> downloading ${base_url}/${archive}"
  curl -fsSL "${base_url}/${archive}" -o "${tmp}/${archive}"

  echo "==> downloading ${base_url}/${checksums_file}"
  curl -fsSL "${base_url}/${checksums_file}" -o "${tmp}/${checksums_file}"

  # The upstream checksums file is a list of "sha256<space>filename" rows
  # for every published archive. Grep for our archive's row and extract
  # the expected digest. ``awk`` collapses any column-padding semantics.
  local expected_sha
  expected_sha="$(awk -v target="${archive}" '$2 == target { print $1 }' \
    "${tmp}/${checksums_file}")"

  if [[ -z "${expected_sha}" ]]; then
    echo "error: ${archive} not found in ${checksums_file}" >&2
    rm -rf "${tmp}"
    exit 1
  fi

  local actual_sha
  actual_sha="$(sha256_of "${tmp}/${archive}")"
  if [[ "${actual_sha}" != "${expected_sha}" ]]; then
    echo "error: trivy archive sha256 mismatch" >&2
    echo "  expected (from upstream ${checksums_file}): ${expected_sha}" >&2
    echo "  actual   (downloaded archive):              ${actual_sha}" >&2
    rm -rf "${tmp}"
    exit 1
  fi
  echo "==> verified trivy archive against upstream checksums"

  tar -xzf "${tmp}/${archive}" -C "${tmp}"
  install -m 0755 "${tmp}/trivy" "${BIN_DIR}/trivy"
  strip_quarantine "${BIN_DIR}/trivy"

  # Preserve Trivy's LICENSE alongside the binary so the distribution
  # carries Apache-2.0 attribution forward. Missing LICENSE is fatal —
  # without it we'd ship Trivy in violation of Apache §4(c).
  if [[ ! -f "${tmp}/LICENSE" ]]; then
    echo "error: trivy archive ${archive} did not contain LICENSE — refusing to install without Apache-2.0 attribution" >&2
    rm -rf "${tmp}"
    exit 1
  fi
  install -m 0644 "${tmp}/LICENSE" "${BIN_DIR}/trivy.LICENSE"

  # NOTICE is genuinely optional: upstream Trivy does not always ship one
  # (e.g. v0.70.0 has no NOTICE), so a missing NOTICE is not an error.
  # Apache §4(d) only fires when a NOTICE file exists upstream.
  if [[ -f "${tmp}/NOTICE" ]]; then
    install -m 0644 "${tmp}/NOTICE" "${BIN_DIR}/trivy.NOTICE"
  fi

  rm -rf "${tmp}"

  # Smoke-test the binary so a corrupted extract doesn't surface only at
  # first scan time.
  if ! "${BIN_DIR}/trivy" --version >/dev/null 2>&1; then
    echo "error: ${BIN_DIR}/trivy is not executable after install" >&2
    exit 1
  fi
}

install_semgrep() {
  local version="$1"
  # Semgrep is published on PyPI; install into a private venv and front it
  # with a tiny shell wrapper at ${BIN_DIR}/semgrep. The wrapper exec's the
  # venv's own launcher — semgrep's launcher uses its own __file__ location
  # to locate sibling tools (pysemgrep, osemgrep), so we cannot copy/move it.
  #
  # Prefer uv (no system Python dependency); fall back to system python3
  # for environments where uv isn't installed yet (e.g. Docker image build).
  local prefix
  prefix="${REPO_ROOT}/.semgrep-${version}"
  if command -v uv >/dev/null 2>&1; then
    uv venv --python 3.11 --seed --quiet "${prefix}"
    uv pip install --python "${prefix}/bin/python" --quiet "semgrep==${version}"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -m venv "${prefix}"
    "${prefix}/bin/pip" install --quiet "semgrep==${version}"
  else
    echo "error: neither uv nor python3 found — cannot install semgrep" >&2
    exit 1
  fi
  cat > "${BIN_DIR}/semgrep" <<EOF
#!/usr/bin/env sh
# Cliff wrapper — exec's the pinned semgrep venv at a known path so the
# python launcher can find its sibling tools (pysemgrep, osemgrep).
exec "${prefix}/bin/semgrep" "\$@"
EOF
  chmod 0755 "${BIN_DIR}/semgrep"
  strip_quarantine "${BIN_DIR}/semgrep"

  # Verify the install resolved to the pinned version. ``semgrep --version``
  # prints just the version on its own line, e.g. ``1.70.0``. If pip
  # silently grabbed a different release (or the venv broke) we want the
  # installer to fail here, not at first scan.
  local resolved
  resolved="$("${BIN_DIR}/semgrep" --version 2>/dev/null \
    | head -n1 | tr -d '[:space:]')"
  if [[ "${resolved}" != "${version}" ]]; then
    echo "error: semgrep version mismatch" >&2
    echo "  expected: ${version}" >&2
    echo "  resolved: ${resolved:-<empty>}" >&2
    exit 1
  fi
  echo "==> verified semgrep --version reports ${resolved}"

  # Preserve Semgrep CE's LICENSE (LGPL-2.1) alongside the wrapper so the
  # distribution carries LGPL-2.1 attribution forward. The LICENSE file is
  # shipped inside the wheel's dist-info; find it without hard-coding the
  # Python version path. Missing LICENSE is fatal — silently shipping
  # Semgrep without its LGPL-2.1 notice would breach LGPL §1.
  local semgrep_license
  semgrep_license="$(find "${prefix}/lib" -maxdepth 4 \
    -path '*/semgrep-*.dist-info/LICENSE*' -type f 2>/dev/null | head -n1)"
  if [[ -z "${semgrep_license}" || ! -f "${semgrep_license}" ]]; then
    echo "error: semgrep ${version} wheel did not ship a LICENSE matching '${prefix}/lib/**/semgrep-*.dist-info/LICENSE*' — refusing to install without LGPL-2.1 attribution" >&2
    exit 1
  fi
  install -m 0644 "${semgrep_license}" "${BIN_DIR}/semgrep.LICENSE"
}

while read -r line; do
  # Trim comments and blank lines.
  line="${line%%#*}"
  line="$(echo "${line}" | xargs)"
  [[ -z "${line}" ]] && continue
  read -r name version <<<"${line}"
  case "${name}" in
    trivy)   install_trivy   "${version}" ;;
    semgrep) install_semgrep "${version}" ;;
    *) echo "unknown scanner ${name}" >&2; exit 1 ;;
  esac
done < "${VERSIONS_FILE}"

echo "==> scanners installed at ${BIN_DIR}"
